using System;

namespace IS4.MultiArchiver.Vocabulary
{
    public static class Graphs
    {
        [Uri(Vocabularies.At)]
        public static readonly GraphUri AutoGenerated;

        [Uri(Vocabularies.At)]
        public static readonly GraphUri HumanLabelled;

        [Uri(Vocabularies.At)]
        public static readonly GraphUri AutoGuessed;

        [Uri(Vocabularies.At)]
        public static readonly GraphUri Metadata;

        static Graphs()
        {
            typeof(Graphs).InitializeUris();
        }
    }
}
