namespace IS4.MultiArchiver.Vocabulary
{
    public enum Vocabularies
    {
        [Uri("http://www.w3.org/1999/02/22-rdf-syntax-ns#")]
        Rdf,
        [Uri("http://www.w3.org/2000/01/rdf-schema#")]
        Rdfs,
        [Uri("http://www.w3.org/2004/02/skos/core#")]
        Skos,
        [Uri("https://w3id.org/security#")]
        Sec,
        [Uri("http://purl.org/dc/terms/")]
        DcTerms,
        [Uri("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#")]
        Nfo,
        [Uri("http://www.semanticdesktop.org/ontologies/2007/01/19/nie#")]
        Nie,
        [Uri("http://schema.org/")]
        Schema,
        [Uri("http://www.w3.org/2011/content#")]
        Cnt,
        [Uri("http://www.w3.org/2000/09/xmldsig#")]
        XmlDSig,
        [Uri("http://www.w3.org/2001/04/xmldsig-more#")]
        XmlDSigMore,
        [Uri("http://www.w3.org/2001/04/xmlenc#")]
        XmlEnc,
        [Uri("http://xmlns.com/foaf/0.1/")]
        Foaf,
        [Uri("http://www.w3.org/2003/12/exif/ns#")]
        Exif,
        [Uri("http://www.w3.org/2001/XMLSchema#")]
        Xsd,
        [Uri("http://www.w3.org/2002/07/owl#")]
        Owl,
        [Uri("http://dbpedia.org/datatype/")]
        Dt,
        [Uri("http://www.iana.org/assignments/media-types/")]
        MediaTypes,
        [Uri("file:///")]
        File,
    }
}
